version: '3'

services:
  app:
    image: nginx:stable-alpine
    networks:
      - leaks_network
    ports:
      - "8666:80"
    volumes:
      - dumps:/usr/share/nginx/html/dumps

volumes:
  dumps:
    external: true

networks:
  leaks_network:
