version: '3'

networks:
  leaks_app:

services:
  app:
    image: nginx:stable-alpine
    networks:
      - leaks_app
    ports:
      - "8666:80"
    volumes:
      - default.conf:/etc/nginx/conf.d/default.conf
      - dumps:/usr/share/nginx/html/dumps
  php:
    image: php:8-fpm
volumes:
  dumps:
    external: true
