version: '3'
services:
  app:
    image: ameeuwsen/leaks:latest
    ports:
      - "8666:80"
    networks:
      - leaks_network
    volumes:
      - leak_dumps:/var/www/html/public/dumps
      - leak_thumbs:/var/www/html/public/thumbs
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname != leader01 ]
volumes:
  leak_thumbs:
    driver: local
    driver_opts:
      type: cifs
      device: "//192.168.50.51/mainSet/.other/dumps/website/thumbs"
      o: "username=aaron,password=R32pearlz994,uid=1000,gid=1000"
  leak_dumps:
    driver: local
    driver_opts:
      type: cifs
      device: "//192.168.50.51/mainSet/.other/dumps/website"
      o: "username=aaron,password=R32pearlz994,uid=1000,gid=1000"
networks:
  leaks_network:
