version: '3'

services:
  app:
    networks:
      - leaks
    ports:
      - "8666:80"
    volumes:
      - dumps:/usr/share/nginx/html/dumps
  php:
    image: 'php:fpm-alpine'
volumes:
  dumps:
    external: true
networks:
  leaks:
    driver: bridge
