version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - leaks_network
    ports:
      - "8666:80"
    volumes:
      - dumps:/usr/share/nginx/html/dumps
  php:
    image: php:fpm-alpine
    networks:
      - leaks_network
volumes:
  dumps:
    external: true

networks:
  leaks_network:
