version: '3'

networks:
  leaks_app:

services:
  leaks_app:
    image: nginx:stable-alpine
    networks:
      - leaks_app
    ports:
      - "8666:80"
    volumes:
      - dumps:/usr/share/nginx/html
