version: '3'

networks:
  leaks_app:

services:
  leaks_app:
    image: nginx:stable-alpine
    networks:
      - leaks_app
    ports:
      - "8666:80"
    volumes:
      - /var/lib/docker/volumes/dumps/_data:/usr/share/nginx/html/dumps
