version: '3'

networks:
  leaks:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - leaks
    ports:
      - "8666:80"
    volumes:
      - dumps:/usr/share/nginx/html/dumps
  php:
    image: php:fpm-alpine
    networks:
      - leaks
volumes:
  dumps:
    external: true
