version: '3'
services:
  app:
    image: ameeuwsen/leaks:latest
    ports:
      - "8666:80"
    networks:
      - leaks_network
    volumes:
      - dumps:/var/www/html/public/dumps
      - leak_thumbs:/var/www/html/public/thumbs
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.hostname==worker01
          - node.hostname==worker02
          - node.hostname==worker03
          - node.hostname==worker04
volumes:
  dumps:
    external: true
  leak_thumbs:
    external: true
networks:
  leaks_network:
