version: '3'
services:
  app:
    image: ameeuwsen/leaks:latest
    ports:
      - "8666:80"
    networks:
      - leaks_network
    volumes:
      - dumps:/usr/share/nginx/html/dumps
volumes:
  dumps:
    external: true
networks:
  leaks_network:
