name: publish
on: [push]
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker Image
        run: |
               docker build . --tag ghcr.io/ameeuwsen/leaks:latest
               docker run ghcr.io/ameeuwsen/leaks:latest
               docker push ghcr.io/ameeuwsen/leaks:latest

